---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: create file
      command: touch /opt/nduka-awx.txt
    
    - firewalld:
        port: 8082/tcp
        permanent: yes
        state: enabled
        zone: public

    - name: reload firewalld
      command: firewall-cmd --reload
